# Dependencies
markdown:         kramdown
kramdown:
  input: GFM
  parse_block_html: true
  syntax_highlighter: rouge

  # Permalinks
permalink:        pretty

# Setup
title:            Avalon
tagline:          "Shaoyi's Blog"
description:      "Shaoyi Zhang's Blog"
url:              https://shaoyizhang.com
baseurl:          ''

# Disqus Comments
disqus_shortname: shaoyizhang-com

author:
  name:           'Shaoyi Zhang'
  url:            'shaoyizhang.com'

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag

paginate: 5

# Custom vars
version:          2.1.0

excerpt_separator: <!--more-->

github:
  repo:           https://github.com/poole/hyde
