# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Avalon
tagline:          "Shaoyi's Blog"
description:      "Shaoyi Zhang's Blog"
url:              shaoyizhang.com
baseurl:          ''

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: shaoyizhang.com

author:
  name:           'Shaoyi Zhang'
  url:            'shaoyizhang.com'

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag

paginate: 5

# Custom vars
version:          2.1.0

excerpt_separator: <!--more-->

github:
  repo:           https://github.com/poole/hyde
